/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cr4_a51;
import java.util.Random;

/**
 *
 * @author ADMIN
 */
public class Rc4_A51UI extends javax.swing.JFrame {
    
//RC4
    public class RC4Cipher {

    private byte[] S = new byte[256];
    private int x = 0;
    private int y = 0;

    // Khởi tạo RC4 với khóa
    public RC4Cipher(byte[] key) {
        init(key);
    }

    // Khởi tạo mảng S dựa trên khóa
    private void init(byte[] key) {
        int keyLength = key.length;

        // Khởi tạo mảng S
        for (int i = 0; i < 256; i++) {
            S[i] = (byte) i;
        }

        int j = 0;
        // Hoán vị mảng S dựa trên khóa
        for (int i = 0; i < 256; i++) {
            j = (j + S[i] + key[i % keyLength]) & 0xFF;
            byte temp = S[i];
            S[i] = S[j];
            S[j] = temp;
        }
    }

    // Tạo một byte keystream tiếp theo
    private byte keyStream() {
        x = (x + 1) & 0xFF;
        y = (y + S[x]) & 0xFF;

        // Hoán vị S[x] và S[y]
        byte temp = S[x];
        S[x] = S[y];
        S[y] = temp;

        // Trả về giá trị keystream tiếp theo
        return S[(S[x] + S[y]) & 0xFF];
    }

    // Mã hóa hoặc giải mã văn bản
    public byte[] process(byte[] text) {
        byte[] result = new byte[text.length];
        for (int i = 0; i < text.length; i++) {
            result[i] = (byte) (text[i] ^ keyStream()); // XOR với keystream
        }
        return result;
    }
    }
//----------------------------------------------------------------------------------------------------
//A5/1
    
    public class A5_1Cipher {
    // Khai báo ba LFSRs với kích thước và bit phản hồi khác nhau
    private int[] LFSR1 = new int[19];
    private int[] LFSR2 = new int[22];
    private int[] LFSR3 = new int[23];
    private final int[] LFSR1_TAPS = {13, 16, 17, 18}; // Các vị trí bit phản hồi của LFSR1
    private final int[] LFSR2_TAPS = {20, 21};         // Các vị trí bit phản hồi của LFSR2
    private final int[] LFSR3_TAPS = {7, 20, 21, 22};  // Các vị trí bit phản hồi của LFSR3

    // Khởi tạo các thanh ghi LFSR với khóa và vector khởi tạo
    public void initialize(int[] key, int[] iv) {
        for (int i = 0; i < 19; i++) LFSR1[i] = key[i % key.length];
        for (int i = 0; i < 22; i++) LFSR2[i] = iv[i % iv.length];
        for (int i = 0; i < 23; i++) LFSR3[i] = key[(i + 11) % key.length];

        for (int i = 0; i < 100; i++) {
            clockLFSRs();  // Làm nóng hệ thống bằng cách clock 100 lần
        }
    }

    // Hàm clock cho cả ba LFSR dựa trên bit đồng bộ hóa (majority bit)
    private void clockLFSRs() {
        int majority = (LFSR1[8] + LFSR2[10] + LFSR3[10]) > 1 ? 1 : 0;
        if (LFSR1[8] == majority) clockLFSR(LFSR1, LFSR1_TAPS);
        if (LFSR2[10] == majority) clockLFSR(LFSR2, LFSR2_TAPS);
        if (LFSR3[10] == majority) clockLFSR(LFSR3, LFSR3_TAPS);
    }

    // Hàm clock một LFSR dựa trên các vị trí bit phản hồi
    private void clockLFSR(int[] lfsr, int[] taps) {
        int feedback = 0;
        for (int tap : taps) {
            feedback ^= lfsr[tap];
        }
        System.arraycopy(lfsr, 1, lfsr, 0, lfsr.length - 1);
        lfsr[lfsr.length - 1] = feedback;
    }

    // Tạo một bit từ A5/1 (keystream bit)
    private int generateKeystreamBit() {
        clockLFSRs();
        return (LFSR1[18] ^ LFSR2[21] ^ LFSR3[22]);
    }

    // Mã hóa hoặc giải mã dữ liệu
    public byte[] process(byte[] data) {
        byte[] result = new byte[data.length];
        for (int i = 0; i < data.length * 8; i++) {
            int keystreamBit = generateKeystreamBit();
            int dataBit = (data[i / 8] >> (7 - (i % 8))) & 1;
            int encryptedBit = dataBit ^ keystreamBit;
            result[i / 8] |= encryptedBit << (7 - (i % 8));
        }
        return result;
    }
    }
    
    
//----------------------------------------------------------------------------------------------------
    /**
     * Creates new form Cr4_A51UI
     */
    public Rc4_A51UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Ctxt_cr4 = new javax.swing.JTextArea();
        Pkeytxt_cr4 = new javax.swing.JTextField();
        btn_encryp_cr4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ptxt_a51 = new javax.swing.JTextArea();
        Ckeytxt_cr4 = new javax.swing.JTextField();
        btn_decryp_cr4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ptxt_cr4 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Ctxt_a51 = new javax.swing.JTextArea();
        btn_encryp_a51 = new javax.swing.JButton();
        btn_decryp_a51 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDecryped_Rc4 = new javax.swing.JTextField();
        txtDecryped_A51 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ctxt_cr4.setColumns(20);
        Ctxt_cr4.setRows(5);
        jScrollPane1.setViewportView(Ctxt_cr4);

        btn_encryp_cr4.setText("Encryp");
        btn_encryp_cr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encryp_cr4ActionPerformed(evt);
            }
        });

        Ptxt_a51.setColumns(20);
        Ptxt_a51.setRows(5);
        jScrollPane2.setViewportView(Ptxt_a51);

        btn_decryp_cr4.setText("Decryp");
        btn_decryp_cr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decryp_cr4ActionPerformed(evt);
            }
        });

        Ptxt_cr4.setColumns(20);
        Ptxt_cr4.setRows(5);
        jScrollPane3.setViewportView(Ptxt_cr4);

        Ctxt_a51.setColumns(20);
        Ctxt_a51.setRows(5);
        jScrollPane4.setViewportView(Ctxt_a51);

        btn_encryp_a51.setText("Encryp");
        btn_encryp_a51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encryp_a51ActionPerformed(evt);
            }
        });

        btn_decryp_a51.setText("Decryp");
        btn_decryp_a51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decryp_a51ActionPerformed(evt);
            }
        });

        jLabel1.setText("RC4");

        jLabel2.setText("A5/1");

        jLabel3.setText("key E:");

        jLabel4.setText("key D:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addComponent(txtDecryped_Rc4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_encryp_cr4)
                            .addComponent(Pkeytxt_cr4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_encryp_a51))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_decryp_cr4)
                                .addGap(133, 133, 133))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ckeytxt_cr4)
                                .addGap(75, 75, 75)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDecryped_A51, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_decryp_a51)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Pkeytxt_cr4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(122, 122, 122)
                            .addComponent(btn_encryp_cr4))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_encryp_a51))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Ckeytxt_cr4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_decryp_cr4)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_decryp_a51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDecryped_A51, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(txtDecryped_Rc4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_encryp_cr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encryp_cr4ActionPerformed
        // TODO add your handling code here:
        byte[] keyBytes = Pkeytxt_cr4.getText().getBytes();
        byte[] plaintextBytes = Ptxt_cr4.getText().getBytes();
        RC4Cipher rc4 = new RC4Cipher(keyBytes);
        byte[] encrypted = rc4.process(plaintextBytes);
        Ctxt_cr4.setText(new String(encrypted));
    }//GEN-LAST:event_btn_encryp_cr4ActionPerformed

    private void btn_decryp_cr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decryp_cr4ActionPerformed
        // TODO add your handling code here:
        byte[] keyBytes = Pkeytxt_cr4.getText().getBytes();
        byte[] plaintextBytes = Ptxt_cr4.getText().getBytes();
        RC4Cipher rc4 = new RC4Cipher(keyBytes);
        byte[] encrypted = rc4.process(plaintextBytes);
        byte[] keyBytes2 = Ckeytxt_cr4.getText().getBytes();
        rc4 = new RC4Cipher(keyBytes2);
        byte[] decrypted = rc4.process(encrypted);
        txtDecryped_Rc4.setText(new String(decrypted));
    }//GEN-LAST:event_btn_decryp_cr4ActionPerformed

    private void btn_encryp_a51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encryp_a51ActionPerformed
        // TODO add your handling code here:
        // Khóa và IV giả lập
        int[] key = new int[19];
        int[] iv = new int[22];
        Random rand = new Random();

        // Sinh ngẫu nhiên khóa và IV
        for (int i = 0; i < key.length; i++) key[i] = rand.nextInt(2);
        for (int i = 0; i < iv.length; i++) iv[i] = rand.nextInt(2);

        // Khởi tạo văn bản
        String plaintext = Ptxt_a51.getText();
        byte[] plaintextBytes = plaintext.getBytes();

        // Khởi tạo A5/1 và mã hóa
        A5_1Cipher a5_1 = new A5_1Cipher();
        a5_1.initialize(key, iv);
        byte[] encrypted = a5_1.process(plaintextBytes);
        Ctxt_a51.setText(new String(encrypted));
    }//GEN-LAST:event_btn_encryp_a51ActionPerformed

    private void btn_decryp_a51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decryp_a51ActionPerformed
        // TODO add your handling code here:
        int[] key = new int[19];
        int[] iv = new int[22];
        Random rand = new Random();

        // Sinh ngẫu nhiên khóa và IV
        for (int i = 0; i < key.length; i++) key[i] = rand.nextInt(2);
        for (int i = 0; i < iv.length; i++) iv[i] = rand.nextInt(2);

        // Khởi tạo văn bản
        String plaintext = Ptxt_a51.getText();
        byte[] plaintextBytes = plaintext.getBytes();

        // Khởi tạo A5/1 và mã hóa
        A5_1Cipher a5_1 = new A5_1Cipher();
        a5_1.initialize(key, iv);
        byte[] encrypted = a5_1.process(plaintextBytes);
        a5_1.initialize(key, iv);
        byte[] decrypted = a5_1.process(encrypted);
        txtDecryped_A51.setText(new String(decrypted));
    }//GEN-LAST:event_btn_decryp_a51ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rc4_A51UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rc4_A51UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rc4_A51UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rc4_A51UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rc4_A51UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ckeytxt_cr4;
    private javax.swing.JTextArea Ctxt_a51;
    private javax.swing.JTextArea Ctxt_cr4;
    private javax.swing.JTextField Pkeytxt_cr4;
    private javax.swing.JTextArea Ptxt_a51;
    private javax.swing.JTextArea Ptxt_cr4;
    private javax.swing.JButton btn_decryp_a51;
    private javax.swing.JButton btn_decryp_cr4;
    private javax.swing.JButton btn_encryp_a51;
    private javax.swing.JButton btn_encryp_cr4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtDecryped_A51;
    private javax.swing.JTextField txtDecryped_Rc4;
    // End of variables declaration//GEN-END:variables

}
